### ISSUE TITLE
Link to CDN for Openlayers v6.1.1 is broken

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree-ogcapi#48]
The HTML view fails to show the OL map due to a HTTP 404 error. 
The version of OL v6.1.1 used in the [demo](http://cite.deegree.org/deegree-ogcapi-1.3/datasets/strassenbaumkataster/collections/strassenbaumkataster) is not available at https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/ anymore.

Error:
Request URL: https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.1.1/build/ol.js
Request Method: GET
Status Code: 404 
Remote Address: 146.75.61.229:443

**Comment by tfr42** [comment]
Snapshot build (WAR file) can be download from https://buildserver.deegree.org/job/ogcapi-pr/job/PR-49/
Snapshot build of Docker images can be downloaded from: https://hub.docker.com/r/deegree/deegree-ogcapi/tags

**Comment by tfr42** [comment]
How to fix the issue manually:

1. Go to the directory of your Servlet container where the WAR file `deegree-ogcapi-webapp-<DB-PROFILE>-<VERSION>.war` is located, for Apache Tomcat it is `CATALINA_HOME/webapps`
2. If the WAR file is already unzipped (exploded archive) then navigate to the subfolder `WEB-INF/lib` otherwise unzip the WAR file first.
3. Unzip the JAR file `deegree-ogcapi-features-<VERSION>.jar`
4. Change in the files `collection.html`, `features.html`, and `feature.html` all occurrences of the URL `https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.1.1/css/ol.css` (old) to `https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.15.1/css/ol.css` (new)
5. Zip the JAR file and replace the old file by the new JAR file.
6. restart your Servlet Container

On Linux with GNU sed, Tomcat and JDK installed you can run the following commands for updating the links (step 3-5):
```
export OGCAPI-VERSION=1.3-SNAPSHOT
cd $CATALINA_HOME/webapps/deegree-ogcapi-webapp-postgres-$OGCAPI-VERSION.war/WEB-INF/lib
jar -xvf deegree-ogcapi-features-$OGCAPI-VERSION.jar features.html feature.html collection.html
sed -i -e 's/v6.1.1/v6.15.1/' *.html
jar -uvf deegree-ogcapi-features-1.3-SNAPSHOT.jar features.html feature.html collection.html
rm features.html feature.html collection.html
```

**Comment by julianzz98** [comment]
The manual changes as well as the usage of the proposed command snippet for the changes were tested locally and work as intended. Additionally the new build was also confirmed to be working with the given infrastructure setup.
