### ISSUE TITLE
Build dependency repository not available

### ISSUE THREAD

**Issue by stempler** [deegree/deegree-ogcapi#77]
**Describe the bug**
Build is failing because repository [public-ogcapi](https://repo.deegree.org/repository/public-ogcapi/) referenced [here](https://github.com/deegree/deegree-ogcapi/blob/32a6fc841e95a46046d4f09f1eae287a8715af1e/pom.xml#L33) seems to be not available.
Is this a temporary issue (e.g. related to maintenance)? Or is this repository no longer available?

**To Reproduce**
Steps to reproduce the behavior
1. Run build with Maven, e.g. `mvn install -DskipTests=true`

**Expected behavior**
The repository for the build dependencies should be available.

**Screenshots**

![Screenshot from 2023-03-10 09-54-46](https://user-images.githubusercontent.com/375475/224271233-9d7c0b46-13da-45be-8044-a3007d6fe574.png)

**Additional context**
I tried using the "public" repository instead, which works in finding the related dependencies, but it seems those are not up-to-date with what the ogcapi project needs, since then the build complains about a missing class `org.deegree.services.config.ApiKey` which cannot be found in the current deegree3 main branch.
What version/branch of deegree is used as source for the ogcapi dependencies?

**Comment by tfr42** [comment]
Hi @stempler,
I've reworked the access privileges for the anonymous user in [repo.deegree.org](https://repo.deegree.org/#browse/browse). The `public-ogcapi` repo should be accessible now.
For your information, we have two separate build jobs configured to build deegree OGC API:
- Build job for the specific [feature branch](https://github.com/lat-lon/deegree3/tree/ogcapi-7240) including all [PR required for OGC API](https://github.com/deegree/deegree3/pulls?q=is%3Apr+label%3AOGCAPI+): https://buildserver.deegree.org/view/deegree-ogcapi/job/deegree-ogcapi-deegree-openjdk11/
- Build job for deegree OGC API itself: https://buildserver.deegree.org/view/deegree-ogcapi/job/deegree-ogcapi-BUILD/

**Comment by stempler** [comment]
Thanks a lot @tfr42 for the quick reaction and fix!
