### ISSUE TITLE
Provide Dockerfile or other instructions for building a Docker image

### ISSUE THREAD

**Issue by stempler** [deegree/deegree-ogcapi#83]
**Is your feature request related to a problem? Please describe.**
I did not find any specific instructions on how the official Docker image is built or how to build the image in general.

**Describe the solution you'd like**
I think it would be helpful to have instructions on building a Docker image as part of the repository.

**Describe alternatives you've considered**
I guess there are many alternatives to building Docker images and that may depend on preferences.
You can find an example of a simple Dockerfile for building a Docker image for the project [here](https://github.com/wetransform-os/deegree-ogcapi/blob/devel/Dockerfile).
With a respective [hook configuration](https://github.com/wetransform-os/deegree-ogcapi/tree/devel/hooks) for Docker Hub, in case the Docker Hub automated build based on its GitHub integration would be an option, image labels on the revision, build date and repository URL can be automatically included.

**Comment by tfr42** [comment]
There are 2 Dockerfiles available:
- https://github.com/deegree/deegree-ogcapi/blob/main/Dockerfile
- https://github.com/deegree/deegree-ogcapi/blob/main/docker/1.3/Dockerfile which is build and pushed automatically every 24 hrs with https://github.com/deegree/deegree-ogcapi/blob/main/.github/workflows/build_docker.yml to https://hub.docker.com/r/deegree/deegree-ogcapi (see also https://github.com/deegree/deegree-ogcapi/discussions/52 for more information)
