### ISSUE TITLE
Nexus repository public-ogcapi misses 3.5.0-SNAPSHOT versions

### ISSUE THREAD

**Issue by stempler** [deegree/deegree-ogcapi#85]
**Describe the bug**
Nexus repository public-ogcapi misses 3.5.0-SNAPSHOT versions. Generally there don't seem to be any snapshot versions - not sure if there were any others before.
This leads to the build failing if the respective artifact was no previously cached.

**To Reproduce**
Try building on clean slate with Maven or check the repository content.

**Expected behavior**
The required build dependencies should be available in the repository.

**Screenshots**

![image](https://user-images.githubusercontent.com/375475/228464906-0ee2ae73-50b1-464b-a14d-cd0cf7cff999.png)

Example error from Maven build:
```
Error:  Failed to execute goal on project deegree-ogcapi-datasets: Could not resolve dependencies for project org.deegree:deegree-ogcapi-datasets:jar:1.3-SNAPSHOT: The following artifacts could not be resolved: org.deegree:deegree-core-commons:jar:3.5.0-SNAPSHOT, org.deegree:deegree-core-workspace:jar:3.5.0-SNAPSHOT: Could not find artifact org.deegree:deegree-core-commons:jar:3.5.0-SNAPSHOT in deegree-ogcapi-repo (https://repo.deegree.org/repository/public-ogcapi/) -> [Help 1]
```

**Comment by tfr42** [comment]
@stempler Thanks for reporting this issue. The nexus policies have been updated and the repo https://repo.deegree.org/repository/public-ogcapi/ should contain all [deegree core](https://github.com/deegree/deegree3) artifacts to build the [deegree ogc api project](https://github.com/deegree/deegree-ogcapi) now.
The build jobs used to build the [feature branch](https://buildserver.deegree.org/view/deegree-ogcapi/job/deegree-ogcapi-deegree-openjdk11/) and the [project itself ](https://buildserver.deegree.org/view/deegree-ogcapi/job/deegree-ogcapi-BUILD/) have completed sucessfully after applying some changes needed after [github changed the host ssh key](https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/).
